# Ejercicios Numpy

In [1]:
import numpy as np

___

## Parte I

- Crea un vector con valores de 10 a 49 en pasos de 0.5.

In [4]:
vec = np.arange(10, 49, 0.5)
vec

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5,
       32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. ,
       37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5,
       43. , 43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. ,
       48.5])

- Muestra su dimensión y su tipo.

In [8]:
vec.ndim

1

In [5]:
vec.shape

(78,)

In [7]:
vec.dtype

dtype('float64')

- Crea un array con los números que tu elijas de dimensiones 2x3.

In [9]:
array = np.array([
    [1,2,3],
    [1,4,2],
])
array

array([[1, 2, 3],
       [1, 4, 2]])

In [10]:
array.shape

(2, 3)

- Redimensiona el array anterior a 3x2

In [11]:
array.reshape(3, 2)

array([[1, 2],
       [3, 1],
       [4, 2]])

### Indexing y slicing:

- Crea un array unidimensional de 10 elemento aleatorios.

In [13]:
uni = np.random.rand(10)
uni

array([0.38644271, 0.45325225, 0.0619773 , 0.81980057, 0.90866902,
       0.38414949, 0.65681897, 0.48866799, 0.58496005, 0.18385408])

In [14]:
uni.shape

(10,)

- Crea un array bidimensional de 10x10 elementos aletorios.

In [17]:
bi = np.random.rand(10, 10)
bi

array([[0.59088774, 0.45361538, 0.3306498 , 0.91339506, 0.15394373,
        0.27050905, 0.61501329, 0.77106614, 0.04682278, 0.91473199],
       [0.32309195, 0.25923714, 0.82470148, 0.40842295, 0.85177219,
        0.4655108 , 0.20479735, 0.35404087, 0.24455733, 0.25521709],
       [0.80243379, 0.26690672, 0.65712176, 0.3039655 , 0.2796802 ,
        0.45606095, 0.28755637, 0.70842763, 0.3423477 , 0.25461512],
       [0.25226316, 0.98923088, 0.98835678, 0.43711909, 0.86554239,
        0.09183082, 0.60088761, 0.48520499, 0.91724657, 0.8299519 ],
       [0.97536852, 0.02950637, 0.2592086 , 0.85771629, 0.73543582,
        0.36839968, 0.47419731, 0.86444186, 0.54894935, 0.97631759],
       [0.63103224, 0.77104798, 0.04547303, 0.60962864, 0.9150481 ,
        0.56964667, 0.89890758, 0.47251695, 0.36562792, 0.00681494],
       [0.91470175, 0.01431332, 0.42018522, 0.58097903, 0.67441152,
        0.21206009, 0.23686671, 0.05661806, 0.46148763, 0.05162179],
       [0.84812415, 0.09295363, 0.3789409

In [18]:
bi.shape

(10, 10)

- Accede al primer elemento y al penúltimo número de cada array. 

In [19]:
uni[0]

0.3864427129499899

In [34]:
bi[0][0]

0.5908877435281612

In [36]:
bi[-1,-2]

0.5156279818989125

- Array unidimensional: muestra todos los elementos en posiciones pares desde la posición 6.

In [39]:
uni[6::2]

array([0.65681897, 0.58496005])

- Array bidimensional: muestra una submatriz con las dos primeras filas y las tres primeras columnas.

In [47]:
bi[:2, :5]

array([[0.59088774, 0.45361538, 0.3306498 , 0.91339506, 0.15394373],
       [0.32309195, 0.25923714, 0.82470148, 0.40842295, 0.85177219]])

- Divide el array bidimensional en dos: uno con las 2 primera filas y otro con las siguientes filas

In [52]:
bi_a = bi[:2]
bi_b = bi[2:]

In [53]:
bi_a

array([[0.59088774, 0.45361538, 0.3306498 , 0.91339506, 0.15394373,
        0.27050905, 0.61501329, 0.77106614, 0.04682278, 0.91473199],
       [0.32309195, 0.25923714, 0.82470148, 0.40842295, 0.85177219,
        0.4655108 , 0.20479735, 0.35404087, 0.24455733, 0.25521709]])

In [54]:
bi_b

array([[0.80243379, 0.26690672, 0.65712176, 0.3039655 , 0.2796802 ,
        0.45606095, 0.28755637, 0.70842763, 0.3423477 , 0.25461512],
       [0.25226316, 0.98923088, 0.98835678, 0.43711909, 0.86554239,
        0.09183082, 0.60088761, 0.48520499, 0.91724657, 0.8299519 ],
       [0.97536852, 0.02950637, 0.2592086 , 0.85771629, 0.73543582,
        0.36839968, 0.47419731, 0.86444186, 0.54894935, 0.97631759],
       [0.63103224, 0.77104798, 0.04547303, 0.60962864, 0.9150481 ,
        0.56964667, 0.89890758, 0.47251695, 0.36562792, 0.00681494],
       [0.91470175, 0.01431332, 0.42018522, 0.58097903, 0.67441152,
        0.21206009, 0.23686671, 0.05661806, 0.46148763, 0.05162179],
       [0.84812415, 0.09295363, 0.37894094, 0.55722738, 0.41816607,
        0.17159954, 0.21413778, 0.19297038, 0.01366528, 0.53002822],
       [0.84120843, 0.14711154, 0.44254469, 0.70189119, 0.74147319,
        0.52485852, 0.98465628, 0.28132293, 0.33695234, 0.36909977],
       [0.90693542, 0.94648303, 0.7442890

- Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la diagonal principal valgan 5 y el resto valgan n.

In [57]:
def fun(n):
    return np.eye(n)*(5-n) + n

In [58]:
fun(6)

array([[5., 6., 6., 6., 6., 6.],
       [6., 5., 6., 6., 6., 6.],
       [6., 6., 5., 6., 6., 6.],
       [6., 6., 6., 5., 6., 6.],
       [6., 6., 6., 6., 5., 6.],
       [6., 6., 6., 6., 6., 5.]])

- Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [63]:
def chess(n, flag=False):
    array = np.zeros((n, n)) if flag else np.ones((n, n))
    array[::2, ::2] = flag
    array[1::2, 1::2] = flag
    return array

In [64]:
chess(10)

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])

In [65]:
chess(10, True)

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

---

## Parte II

-  Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [66]:
def matrix(n=10, m=10, trp=False):
    mat = np.arange(n*m).reshape((n, m))
    return mat.T if trp else mat

In [70]:
matrix(10, 5, trp=True)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

- Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [71]:
def neg_check(matrix):
    return (matrix < 0).any()

In [79]:
matriz = np.random.randint(-10, 10, (100,100))
neg_check(matriz)

True

-  Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [82]:
def sum_neg(matrix):
    if neg_check(matrix):
        idx = matrix<0
        result = np.abs(matrix[idx]).sum()
    else:
        result = 'No hay negativos'
    return result

def sum_neg_fast(matrix):
    if neg_check(matrix):
        idx = matrix<0
        result = - matrix[idx].sum()
    else:
        result = 'No hay negativos'
    return result

In [83]:
%%timeit
sum_neg(matriz)

104 µs ± 4.87 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [84]:
%%timeit
sum_neg_fast(matriz)

94 µs ± 4.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


---

## Parte III

- Crea un vector de 30 elementos aleatorios y calcula su media.

In [85]:
vec = np.random.random(30)

In [87]:
np.mean(vec)

0.49486108327666706

In [88]:
vec.mean()

0.49486108327666706

- Crea una matriz de 4x8 aleatoria y substrae la media por columnas.

In [89]:
matriz = np.random.randint(1, 10, (4,8))
matriz

array([[7, 1, 4, 4, 4, 5, 1, 5],
       [7, 9, 6, 7, 6, 5, 9, 6],
       [8, 4, 5, 6, 2, 9, 6, 5],
       [9, 9, 3, 4, 1, 9, 1, 8]])

In [90]:
matriz.shape

(4, 8)

In [ ]:
np.mean()

In [93]:
matriz.mean(axis=0, keepdims=True)

array([[7.75, 5.75, 4.5 , 5.25, 3.25, 7.  , 4.25, 6.  ]])

In [97]:
matriz - matriz.mean(axis=0, keepdims=True)

array([[-0.75, -4.75, -0.5 , -1.25,  0.75, -2.  , -3.25, -1.  ],
       [-0.75,  3.25,  1.5 ,  1.75,  2.75, -2.  ,  4.75,  0.  ],
       [ 0.25, -1.75,  0.5 ,  0.75, -1.25,  2.  ,  1.75, -1.  ],
       [ 1.25,  3.25, -1.5 , -1.25, -2.25,  2.  , -3.25,  2.  ]])

In [98]:
_.sum(axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0.])

- Crea una función que reciba dos enteros n y m, genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn y haga el producto matricial de ambas para obtener una matriz nxn. Deberá devolver una tupla con las tres matrices.

In [103]:
def mul(n, m):
    x = np.random.normal(size=(n, m))
    y = np.random.normal(size=(m, n))
    return x, y, np.dot(x,y)

In [104]:
mul(2, 3)

(array([[ 0.72163424,  0.13859904, -0.45517192],
        [-0.74110278,  0.09542724,  0.24158645]]),
 array([[-0.29784736, -0.28615218],
        [ 0.25615703,  1.03020824],
        [ 0.42031709,  1.2461885 ]]),
 array([[-0.37075027, -0.63094135],
        [ 0.34672278,  0.61144036]]))

- Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la unión de los elementos únicos de ambas.

In [105]:
x = np.random.randint(1, 10, (2,2))
y = np.random.randint(1, 10, (8,10))

In [106]:
np.unique(x)

array([3, 4, 6])

In [107]:
np.unique(y)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
inter = np.intersect1d(x,y)
inter.sort()
inter

array([3, 4, 6])

- Cree una matriz aleatoria normal de 5x10 y normalícela en media y varianza por filas y por columnas (restar la media y dividir entre la desviación típica).

In [109]:
x = np.random.rand(5, 10)

y = x  - x.mean(axis=0)
y = y / x.std(axis=0)

In [110]:
y = x  - x.mean(axis=1, keepdims=True)
y = y / x.std(axis=1, keepdims=True)

In [111]:
np.mean(y)

-6.661338147750939e-18

In [112]:
np.std(y)

1.0