# NumPy I

- Librería eficiente para cálculo numérico
- Creada en 2005 a partir de otras librerías (Numeric y Numarray)
- Contenedores de arrays N-dimensionales
- [Documentación oficial](https://numpy.org/)

- Instalamos con `conda install numpy`
- Reiniciar el kernel para que se reconozca una librería que acabamos de instalar (puede que no sea necesario)

In [1]:
import numpy as np

## Numpy Arrays

- Es rápido para operaciones vectorizadas

In [4]:
lista = list(range(int(1e6)))

In [5]:
%%timeit
lista_2 = [x * 2 for x in lista]

52.2 ms ± 481 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
array = np.arange(int(1e6))

In [9]:
%%timeit #Es mucho más rápido usando el array que lo otro
array_2 = array * 2

616 µs ± 29.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


- Un numpy array puede contener elementos de **cualqueir tipo**
- Todos los elementos de un numpy array deben ser del **mismo tipo**

In [2]:
array = np.array([[5, 15, 10], [0.1, 7, 27]]) #Crea una lista de listas

In [14]:
array

array([[ 5. , 15. , 10. ],
       [ 0.1,  7. , 27. ]])

- Para saber el número y el tamaño de las dimensiones del array podemos usar `ndim` y `shape` respectivamente

In [15]:
array.ndim

2

In [18]:
array.shape # Tiene 2 filas por 3 columnas

(2, 3)

In [24]:
array.size #El tamaño del array

6

- Para saber el tipo de los elementos almacenados usamos `dtype`

In [19]:
array.dtype

dtype('float64')

- El tamaño de los ndarray se define al crearlo y no puede modificarse
- Pero sus dimensiones sí pueden modificarse, siempre y cuando no añadamos más elementos
    - `reshape` -> No es **inplace**
    - `resize` -> Es **inplace**

In [20]:
array.reshape(3, 2)

array([[ 5. , 15. ],
       [10. ,  0.1],
       [ 7. , 27. ]])

In [21]:
array

array([[ 5. , 15. , 10. ],
       [ 0.1,  7. , 27. ]])

In [22]:
array.resize(3,2)

In [23]:
array #Si lo deja modificado, cuidado!

array([[ 5. , 15. ],
       [10. ,  0.1],
       [ 7. , 27. ]])

- Las operaciones se vectorizan automáticamente

In [25]:
array * 2

array([[10. , 30. ],
       [20. ,  0.2],
       [14. , 54. ]])

## Creación de numpy arrays (ndarrays)

- A partir de una lista de Python
- Crearemos un numpy array con dimensiones acordes a las anidaciones de la lista

In [26]:
lista = [ #recordatorio, la lista debe tener los mismos tipos de datos: float, int...
    [2.15, 0, -1.3],
    [-82.45, 41, -0.86],
    [85, 15.2, 23.5],
    [0.12, 7.91, -4.68]
]
array = np.array(lista)
array

array([[  2.15,   0.  ,  -1.3 ],
       [-82.45,  41.  ,  -0.86],
       [ 85.  ,  15.2 ,  23.5 ],
       [  0.12,   7.91,  -4.68]])

- `dtype` -> Tipo del contenido
- `ndim` -> Número de dimensiones
- `shape` -> Estructure
- `size` -> Número total de elementos

In [3]:
array.dtype

dtype('float64')

In [4]:
array.ndim

2

In [29]:
array.shape

(4, 3)

In [30]:
lista2 = [
    [2, 0, -1],
    [-82, 41, -0],
    [85, 15, 23],
    [0, 7, -4]
]
array2 = np.array(lista2)
array2

array([[  2,   0,  -1],
       [-82,  41,   0],
       [ 85,  15,  23],
       [  0,   7,  -4]])

In [31]:
array2.dtype

dtype('int64')

- Hay que tener en cuenta que estos tipos de datos (`dtype('float64')`, `dtype('int64')`, ...) no son los mismos tipos que los tipos built-in de Python (`float`, `int`, ...).

- Podemos crear arrays predeterminados usando las siguientes funciones

In [32]:
np.zeros((5, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros(15, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
np.ones((7,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
np.empty((2, 8))

array([[0.00000000e+000, 5.02034658e+175, 2.02373686e-052,
        2.57905862e-057, 2.98783202e-032, 3.37549284e-057,
        5.01163109e+217, 5.49419094e-143],
       [9.80058441e+252, 1.30304358e-142, 2.14027814e+161,
        7.68724739e+170, 4.30438132e-096, 9.08366793e+223,
        1.72425313e-047, 2.03923757e+184]])

In [36]:
%%timeit
np.zeros((10**4, 10**4))

2.86 µs ± 25.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
%%timeit
np.empty((10**4, 10**4))

2.86 µs ± 41.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
np.eye(4) #Matriz diagonal de identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- Existe una función similar a `range()` pero que devuelve un numpy array `arange()`

In [41]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

- Si queremos un numpy array de valores equiespaciados usamos `linspace()`

In [42]:
np.linspace(2.15, 3.8, 20) #Se usa mucho para plotear, 20 número espaciados entre 2.15 y 3.8

array([2.15      , 2.23684211, 2.32368421, 2.41052632, 2.49736842,
       2.58421053, 2.67105263, 2.75789474, 2.84473684, 2.93157895,
       3.01842105, 3.10526316, 3.19210526, 3.27894737, 3.36578947,
       3.45263158, 3.53947368, 3.62631579, 3.71315789, 3.8       ])

- Fórmula para intervalos equiespaciados en $\Delta x$ elementos

$$N = \frac{(x_\text{max} - x_\text{min})}{\Delta x} \, + \, 1$$

donde $N$ es el número de elementos que podemos pasarle a `np.linspace`, $x_{max}$ y $x_{min}$ son los extremos del intervalo que estamos considerando.

In [43]:
np.linspace(2.0, 3.8, round((3.8-2.0)/0.1+1))

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8])

## Tipos de datos en numpy arrays

| Tipo | Código | Descripción |
|-|-|-|
|`int8`|`i1`|Entero de 8 bits con signo|
|`int16`|`i2`|Entero de 16 bits con signo|
|`int32`|`i4`|Entero de 32 bits con signo|
|`int64`|`i8`|Entero de 64 bits con signo|
|`uint8`|`u1`|Entero sin signo de 8 bits con signo|
|`uint16`|`u2`|Entero sin signo de 16 bits con signo|
|`uint32`|`u4`|Entero sin signo de 32 bits con signo|
|`uint64`|`u8`|Entero sin signo de 64 bits con signo|
|`float16`|`f2`|Coma flotante de 16 bits (baja precisión)|
|`float32`|`f4`|Coma flotante de 32 bits|
|`float64`|`f8`|Coma flotante de 64 bits (doble precisión)|
|`float128`|`f16` o `g`|Coma flotante de 128 bits (precisión extendida)|
|`complex64`|`c8`|Número complejo en coma flotante de 32 bits|
|`complex128`|`c16`|Número complejo en coma flotante de 64 bits|
|`complex256`|`c32`|Número complejo en coma flotante de 128 bits|
|`bool`|`?`|Valor booleano: True or False|
|`string_`|`S`|String de longitud fija|
|`unicode_`|`U`|String unicode de longitud fija|
|`object`|`O`| Objeto de Python|

- Podemos consultar los valores máximo y mínimos (precisión, ...) que podemos almacenar en tipos `int` y `float` con las funciones `iinfo` y `finfo` respectivamente.

In [44]:
np.iinfo(np.int8) #Los número enteros que puedo definir, por ejemplo cuando definolos datos para ahorrar memoria

iinfo(min=-128, max=127, dtype=int8)

In [45]:
tipos_int = [np.int8, np.int16, np.int32, np.int64]
for tipo in tipos_int:
    print(np.iinfo(tipo))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [46]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [47]:
tipos_float = [np.float16, np.float32, np.float64]
for tipo in tipos_float:
    print(np.finfo(tipo))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   e

- Al crear un numpy array, se asigna un tipo por defecto en función de los elementos que contiene

In [5]:
array = np.array([2, 3]) #Si no le digo el tipo lo infiere
array

array([2, 3])

In [6]:
array.dtype

dtype('int64')

- Si el array tiene un tipo por defecto, no se muestra en pantalla

In [51]:
array = np.array([2, 3], dtype='int32')
array

array([2, 3], dtype=int32)

- En caso contrario, sí se muestra

In [52]:
array = np.array([2, 3], dtype=np.int16)
array

array([2, 3], dtype=int16)

In [53]:
array2 = np.array([2, 3, 152], dtype='S5')
array2

array([b'2', b'3', b'152'], dtype='|S5')

In [54]:
array2.nbytes

15

In [55]:
np.array([2, 3], dtype='U5')

array(['2', '3'], dtype='<U5')

In [56]:
np.array([2, 3, 'buenos días'])

array(['2', '3', 'buenos días'], dtype='<U21')

In [57]:
np.array([2, 3, 'buenos días'], dtype='object') #Las strings las devuelve como tipo objeto

array([2, 3, 'buenos días'], dtype=object)

- Podemos cambiar el tipo de un numpy array ya creado con la función `astype()`

In [7]:
rango = np.arange(100)
rango_obj = rango.astype('object')

In [61]:
%%timeit
rango * 2

655 ns ± 12.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [62]:
%%timeit
rango_obj * 2

2.76 µs ± 41.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


- Tamaño en memoria de un numpy array (en bytes, **1 byte = 8 bits**)

In [63]:
array = np.array([2, 3], dtype='int32')
array

array([2, 3], dtype=int32)

In [64]:
array.nbytes

8

In [65]:
array.size * array.itemsize

8

In [66]:
array2 = np.array([2, 3], dtype=np.int16)
array2

array([2, 3], dtype=int16)

In [67]:
array2.nbytes

4

In [68]:
array3 = np.array([2.15, 3.25], dtype='float64')
array3

array([2.15, 3.25])

In [69]:
array3.nbytes

16

- Los numpy array poseen multitud de métodos que se van descubriendo a medida que se van necesitando

In [8]:
from utils import midir

In [9]:
midir(array)

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

- Pasar un array a una lista de Python

In [73]:
array.tolist()

[2, 3]

- Trasposición

In [74]:
array = np.arange(12)
array = array.reshape(3,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
array.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [76]:
array.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [77]:
array[1:].cumprod()

array([      4,      20,     120,     840,    6720,   60480,  604800,
       6652800])

In [78]:
bool_array = np.array([True, True, False, False])

In [10]:
bool_array.any() #¿Hay alguno verdadero?

NameError: name 'bool_array' is not defined

In [80]:
bool_array.all() #¿Son todos verdaderos?

False

## Operaciones aritméticas y lógicas

- Los numpy arrays se basan en la vectorización de operaciones
- Si los numpy arrays tienen la misma dimensión y estrucutra las operaciones aritméticas se realizan elemento a elemento (point-wise/element-wise operations).

In [81]:
array_1 = np.array([
    [1, 2, 3],
    [4, 5, 6.]
])

array_2 = np.array([
    [2, 6, 12],
    [15, 3, 8.]
])

In [82]:
array_1 + array_2

array([[ 3.,  8., 15.],
       [19.,  8., 14.]])

In [83]:
array_1 - array_2

array([[ -1.,  -4.,  -9.],
       [-11.,   2.,  -2.]])

In [84]:
array_1 * array_2

array([[ 2., 12., 36.],
       [60., 15., 48.]])

In [85]:
array_1 / array_2

array([[0.5       , 0.33333333, 0.25      ],
       [0.26666667, 1.66666667, 0.75      ]])

In [86]:
1 / array_1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [87]:
array_1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [88]:
array_1 > array_2 #Para comparar si los elementos son igual en los dos array

array([[False, False, False],
       [False,  True, False]])

- Si los arrays no tienen la misma dimensión, numpy realiza lo que se conoce como **broadcasting**.
- Se repite el array más pequeño hasta obtener un numpy array de las misma dimensiones que el otro.
- Las dimensiones tienen que encajar!!!!

In [89]:
array_1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [90]:
array_3 = np.array([2, 3, 4])
array_3

array([2, 3, 4])

In [92]:
array_1 + array_3 

array([[ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [93]:
array_1 * array_3

array([[ 2.,  6., 12.],
       [ 8., 15., 24.]])

In [94]:
array_4 = np.array([2, 3]) #No puede porque es dimensión diferente y es par con impar, pero cuidado.

In [95]:
array_1 + array_4

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [96]:
array_1 + array_4.T #Falla porque son dimensiones diferentes

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [100]:
array_4 = array_4.reshape(1, 2) #Error muy común
array_4

array([[2, 3]])

In [99]:
array_1 + array_4 #sigue dando el fallo

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [101]:
array_1 + array_4.T #Ahora sí, porque quería sumar la trasposión

array([[3., 4., 5.],
       [7., 8., 9.]])

In [99]:
array_5 = np.ones((2,4))
array_5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [100]:
array_6 = np.array([[1, 2]])
array_6

array([[1, 2]])

In [101]:
array_5 * array_6

ValueError: operands could not be broadcast together with shapes (2,4) (1,2) 

In [102]:
array_5 * array_6.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.]])

## Indexación de arrays

- En arrays unidimensionales la indexación funciona igual que en las listas de Python

In [11]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
array[0]

0

In [104]:
len(array)

10

In [105]:
array[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [106]:
array[1:3]

array([1, 2])

In [107]:
array[1::2]

array([1, 3, 5, 7, 9])

- Podemos modificar parte de los arrays mediante indexación

In [108]:
array[5:] = 0

In [109]:
array

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

- Cuidado con los punteros y la memoria de Python

In [13]:
array_slice = array[:3]
array_slice

array([0, 1, 2])

In [14]:
array_slice[:] = np.zeros(3)

In [15]:
array_slice

array([0, 0, 0])

In [16]:
array

array([0, 0, 0, 3, 4, 5, 6, 7, 8, 9])

- Si machacamos la variable sin indexar, esto no pasa

In [17]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
array_slice = np.ones(3)
array_slice

array([1., 1., 1.])

In [19]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- En numpy arrays multidimensionales podemos indexar de dos formas
    - **Indexación recursiva**
    - **Indexación con comas** (más usado)

In [23]:
array_2d = np.arange(9).reshape(3,3)
array_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
array_2d[1,0] #Este es el que se usa más, el anterior, no

3

In [25]:
array_2d[1][0]

3

In [27]:
array_2d[1:][-1]

array([6, 7, 8])

- Indexación y slicing booleano
    - Muy útil
    - En R también se usa mucho
- Creamos un array booleano de la misma dimensión que el original y lo usamos para extraer las posiciones que sean True

In [28]:
data = np.random.randn(3,4)
data

array([[-0.58222544,  0.39615965,  0.76758283, -1.22089286],
       [ 0.5468972 , -1.05937982,  0.21149437,  0.53885304],
       [-2.53441155, -0.40778279,  0.53906131,  1.26023364]])

In [29]:
data > 0

array([[False,  True,  True, False],
       [ True, False,  True,  True],
       [False, False,  True,  True]])

In [125]:
data[data>0] #Dame los datos que sean mayores que 0, muy útil!!!!!!!

array([1.52669263, 1.24471031, 0.21769727, 0.4836392 , 1.49413356,
       1.1342857 , 0.14008459])

- Podemos negar el índice con `~`

In [126]:
data[~data>0] # Da error, porque los números no se pueden invertir

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [127]:
data[~(data>0)] #Pero sí se puede  invertir el True o False

array([-1.09716469, -1.03635941, -0.89974981, -0.80809437, -0.94649958])

- A estos arrays de booleanos con la misma dimensión que el array original se denominan **máscaras** (**mask**)

In [30]:
data.round() == 1 #Dame los números redondeados que son 1

array([[False, False,  True, False],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [31]:
mask = data > 0 and data.round() == 1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
mask = (data > 0) and (data.round() == 1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
mask = data > 0 & data.round() == 1

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [34]:
mask = (data > 0) & (data.round() == 1) #Poniendo paréntesis y usando el &, no el and

In [35]:
mask

array([[False, False,  True, False],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [136]:
data[mask] #Te muestra dichos datos

array([1.24471031, 1.49413356, 1.1342857 ])

- Indexación con secuencias de enteros

In [137]:
array = np.arange(27).reshape(3,3,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [138]:
array[[1, 2]]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
array[[1, 2], [0,1]]

array([[ 9, 10, 11],
       [21, 22, 23]])

In [140]:
array[[1, 2], [0,1], [1]]

array([10, 22])

- En general, si tenemos que indexar un array es preferible hacerlo de una forma que sea independiente de la posición de los objetos.
    - Con máscaras booleanas por ejemplo.
- Una indexación compleja no es fácilmente mantenible ni es garantía de seguridad ante posibles cambios de los datos de entrada.

## Random numbers con Numpy

- Aunque podemos generar números aleatorios con el paquete core de Python `random`, Numpy trae su propio generador de números aleatorios `np.random`
- Estos generadores devuelven numpy arrays

|Función|Descripcción|
|----|---|
|`seed`| Semilla del generador de números aleatorios.|
|`permutation`| Permutación aleatoria de una secuencia de entrada.|
|`shuffle`| Permutación aleatoria de la secuencia de entrada (inplace).|
|`rand`|  Muestra de números aleatorios utilizando una **distribución uniforme** entre 0 y 1.|
|`randint`|  Muestra de números aleatorios enteros dentro de un rango definido.|
|`randn`|  Muestra de números aleatorios utilizando una distribución **normal** de media 0 y desviación 1.|
|`binomial`| Muestra de números aleatorios utilizando una distribución **binomial**.|
|`normal`| Muestra de números aleatorios utilizando una distribución **normal**.|
|`beta`| Muestra de números aleatorios utilizando una distribución **beta**.|
|`chisquare`| Muestra de números aleatorios utilizando una distribución **chi cuadrado**.|
|`gamma`|  Muestra de números aleatorios utilizando una distribución **gamma**.|
|`uniform`| Muestra de números aleatorios utilizando una distribución **uniforme** [0, 1). |

In [141]:
array = np.arange(10)

In [142]:
np.random.permutation(array)

array([0, 5, 8, 3, 1, 7, 9, 6, 4, 2])

In [143]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
np.random.shuffle(array)

In [145]:
array

array([8, 9, 6, 3, 1, 0, 5, 2, 4, 7])

In [146]:
%%timeit
np.random.permutation(array)

25.5 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [148]:
%%timeit #Lo hace más rápido porque lo hace inplace, suele ocurrir
np.random.shuffle(array)

19.8 µs ± 372 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [149]:
import random

In [150]:
%%timeit
random.shuffle(array)

6.96 µs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [151]:
array_list = list(array)

In [152]:
%%timeit
random.shuffle(array_list)

5.54 µs ± 861 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


- En general es mucho más rápida que la librería original

In [153]:
N = 10**6
%timeit [random.normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N) #Mucho más rápido esto

535 ms ± 8.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
23.4 ms ± 2.36 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [154]:
np.random.normal(loc=4, scale=2, size=(5,2))

array([[ 1.47485851, -1.55219391],
       [ 3.16330108,  0.31108458],
       [ 2.63018727,  2.4618592 ],
       [ 0.9809311 ,  6.2010662 ],
       [ 5.86979211,  8.67075336]])

- Podemos fijar una semilla para obtener siempre los mismos números aleatorios
- La semilla hay que fijarla cada vez que llamemos a una función aleatoria

In [156]:
np.random.seed(1223) #La semilla es lo que enchufas primero para que sea aleatorio,
                        #porque los ordenadores no pueden general números aleatorios
                        #Se suele generar la semilla ahora

In [158]:
np.random.normal(0)

0.10773472048723803

In [36]:
np.random.seed(1223)
np.random.normal(0) #Asi la he fijado, así se general los mismos número aleatorios.

-1.247332073628074

In [37]:
np.random.normal(0) #Sin semilla, siempre te da diferente

0.10773472048723803