# Ejercicios Numpy

In [2]:
import numpy as np

___

## Parte I

- Crea un vector con valores de 10 a 49 en pasos de 0.5.

In [72]:
vector = np.arange(10, 49, 0.5)
vector

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5,
       32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. ,
       37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5,
       43. , 43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. ,
       48.5])

- Muestra su dimensión y su tipo.

In [69]:
vector.shape

(39,)

In [68]:
vector.dtype

dtype('int64')

- Crea un array con los números que tu elijas de dimensiones 2x3.

In [25]:
array = np.array([[3,6,5], [13,20,15]])

In [26]:
array

array([[ 3,  6,  5],
       [13, 20, 15]])

- Redimensiona el array anterior a 3x2

In [27]:
array.reshape(3, 2)

array([[ 3,  6],
       [ 5, 13],
       [20, 15]])

### Indexing y slicing:

- Crea un array unidimensional de 10 elemento aleatorios.

In [32]:
np.random.random(10)


array([0.32691411, 0.3320704 , 0.10018695, 0.11253071, 0.86972505,
       0.06022083, 0.91756527, 0.17596578, 0.85172036, 0.97627792])

In [30]:
np.random.normal(34,5,10)

array([189, 168,  50, 227,  60, 158, 141,  48,  57, 188])

In [31]:
np.random.randint(1, 233, 10) #Para números enteros

array([ 44,  17, 139, 149,   2,  76,  49, 164,  20,  46])

- Crea un array bidimensional de 10x10 elementos aletorios.

In [42]:
array2 = np.random.randint(1, 10, size=(10,10))
array2

array([[5, 2, 9, 8, 7, 8, 8, 3, 3, 5],
       [9, 3, 3, 6, 8, 9, 4, 3, 5, 4],
       [5, 5, 1, 9, 7, 2, 9, 3, 2, 6],
       [3, 4, 6, 7, 7, 6, 3, 2, 7, 3],
       [9, 1, 2, 5, 9, 1, 5, 9, 8, 2],
       [1, 7, 1, 5, 1, 4, 6, 5, 1, 2],
       [8, 4, 6, 7, 8, 9, 1, 8, 4, 2],
       [9, 9, 2, 5, 2, 3, 6, 2, 3, 8],
       [6, 4, 5, 6, 6, 4, 6, 4, 7, 5],
       [6, 1, 3, 3, 1, 3, 4, 9, 7, 5]])

- Accede al primer elemento y al penúltimo número de cada array. 

In [44]:
arrays_sel = array2[0,0], array2[-1,-2]
arrays_sel

(5, 7)

- Array unidimensional: muestra todos los elementos en posiciones pares desde la posición 6.

In [60]:
print(vector)
vector [6::2]

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5]


array([13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48.])

- Array bidimensional: muestra una submatriz con las dos primeras filas y las tres primeras columnas.

In [74]:
array2[:2, :3]

array([[1, 7, 5],
       [8, 9, 1]])

- Divide el array bidimensional en dos: uno con las 2 primera fila y otro con las siguientes filas

- Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la diagonal principal valgan 5 y el resto valgan n.

- Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

---

## Parte II

-  Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [124]:
def fun(n,m, gen=False): #Funciona!! hecho por mi
    if gen == False:
        return np.arange(n*m).reshape(n,m)
    if gen ==True:
        return np.arange(n*m).reshape(n,m).T
    

In [125]:
fun(5,5, False)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [126]:
fun(5,5, True)

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

- Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [109]:
def neg_check(matriz):
    return (matriz < 0).any()

In [110]:
print(matriz2)
neg_check(matriz2)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

-  Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

---

## Parte III

- Crea un vector de 30 elementos aleatorios y calcula su media.

In [50]:
np.random.seed(1234) #Para que se mantenga
vector = np.random.randint(0,50, size=(4,8))
vector.mean()

array([[47, 19, 38, 12, 24, 15, 49, 23],
       [41, 26, 30, 43, 30, 44, 26, 48],
       [28,  5, 16,  9, 47, 48, 12, 37],
       [34, 38,  3, 39, 11,  0, 41, 11]])

- Crea una matriz de 4x8 aleatoria y substrae la media por columnas.

In [150]:
vector2 = np.random.randint(0,50, size=(4,8))
np.mean(vector2, 0) #Axes = Dimensiones 0 o 1

array([31.25, 30.25, 20.25, 19.  , 28.5 , 35.5 , 22.5 , 24.  ])

In [169]:
vector2.mean(axis=0, keepdims=True)

array([[31.25, 30.25, 20.25, 19.  , 28.5 , 35.5 , 22.5 , 24.  ]])

- Crea una función que reciba dos enteros n y m, genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn y haga el producto matricial de ambas para obtener una matriz nxn. Deberá devolver una tupla con las tres matrices.

In [ ]:
ent1 = 4 #Sin terminar!!!!!!
ent2 = 2
def gen_mat(n,m):
    mat1 = np.random.randint(0,1, size=(n,m))
    mat2 = np.random.randint(0,1, size=(m,n))
    return mat1, mat2
    

- Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la unión de los elementos únicos de ambas.

In [159]:
def gen_mat(n,m): #Sin terminar!!!! falta lo de los elementos únicos.
    mat1 = np.random.randint(0,100, size=(n,m))
    mat2 = np.random.randint(0,100, size=(n,m))
    matfinal = np.union1d(mat1, mat2)
    return np.sort(matfinal)

In [160]:
gen_mat(3,2)

array([ 7, 13, 18, 22, 29, 47, 49, 57, 58, 67])

In [165]:
mat1 = np.random.randint(0,100, size=(3,2))
mat2 = np.random.randint(0,100, size=(3,2))
print(mat1)
print(mat2)
np.union1d(mat1, mat2)

[[ 0 21]
 [36 90]
 [53  9]]
[[45 99]
 [84 53]
 [10 92]]


array([ 0,  9, 10, 21, 36, 45, 53, 84, 90, 92, 99])

- Cree una matriz aleatoria normal de 5x10 y normalícela en media y varianza por filas y por columnas (restar la media y dividir entre la desviación típica).